### ISSUE TITLE
DOM interface vs html attribute

### ISSUE THREAD

**Issue by HolgerJeromin** [WICG/gesture-delegation#1]
I am surprised to see that the naming of the matching DOM interface and html attribute is so different. Or is the documentation not up to date?

https://sites.google.com/a/chromium.org/dev/audio-video/autoplay mentions `gesture=media` attribute.

This document mentions a `allowedGestureDelegation` DOM interface.

**Comment by mounirlamouri** [comment]
Thanks for your feedback. The wiki page is using a placeholder name. We will update it when the final name has launched.

**Comment by HolgerJeromin** [comment]
What???
You were using a placeholder without a warning? This should be changed asap so developers does not use and remember an attribute name without effect.
This update in M64 got already a lot of press coverage and devs (like me) are adapting websites already.

**Comment by evanestal** [comment]
Can we test this in Canary (or anywhere?) yet?  We're trying to get in front of this change for a K-12 edtech site used by millions of US schoolkids.   We use autoplay video and audio in many places (often launched in iFrames) where we used to use Flash.  Autoplay is not working.  We're getting loads of "An AudioContext in a cross origin iframe must be created or resumed from a user gesture to enable audio output." despite trying to use this tag while testing in Canary.
