### ISSUE TITLE
Finalise attribute name to be clear and short

### ISSUE THREAD

**Issue by annevk** [WICG/gesture-delegation#7]
The new name doesn't convey it's a new primitive.

**Comment by mounirlamouri** [comment]
Which name is this? The name of the attribute? Happy to name it `delegateDocumentUserActivation` but that's a mouthful :-/

**Comment by annevk** [comment]
Yeah, not sure. @domenic?

Given the blink-dev thread I guess the main problem is that what Chrome is doing is something novel and now features are being created around that rather novel approach without it really being proven.

**Comment by mounirlamouri** [comment]
I agree that's a concern but I think this is important in order for those new concepts to be used and proven wrong or right. Because it's only an attribute, I think the risk for the platform is low. The worse case is that this attribute will never be supported by other browsers because they will never adopt these new concepts but I think that's a discussion larger than this work.

**Comment by domenic** [comment]
Sigh, naming things.

I don't really understand the document vs. not bit.

I am confused as to why this uses the allow prefix when it's not an allow* attribute, at least according to the explainer. Will it reuse the [allowed to use](https://html.spec.whatwg.org/#allowed-to-use) algorithm and the [set the allow* flags](https://html.spec.whatwg.org/#set-the-allow*-flags) infrastructure somehow, in some hybrid token list form or something?

**Comment by mounirlamouri** [comment]
It will probably re-use part of the algorithms you mentioned but I don't think we have to prefix with `allow`. What about: `delegateDocumentActivationFor`?

**Comment by domenic** [comment]
Per https://github.com/WICG/gesture-delegation/issues/10#issuecomment-338226514 I now understand the "document" usage but think it's very bad. Maybe we can get away from saying where it's stored and instead describe it with something like `delegateStickyUserActivation`.

**Comment by mounirlamouri** [comment]
s/document/sticky/ sounds good to me. What about dropping "user" (to shorten) and adding "for". I'm afraid developers might not quite understand it's not a boolean attribute otherwise.

**Comment by domenic** [comment]
I think we should keep user as we spread the string "user activation" throughout more and more public APIs, for consistency.

I'm not sure about "for". I don't think we have a precedent of using something like that to signal a token list. It'd be worth surveying other attribute names. iframe sandbox comes to mind, but it has kind of the opposite model, of all things by default with opt-outs.

**Comment by mounirlamouri** [comment]
`delegateStickyUserActivation` works for me then. @annevk are you happy with this name?

**Comment by annevk** [comment]
Sure. (With for there's precedent for it taking an ID, so I think not having that in the name is better.)

**Comment by mounirlamouri** [comment]
Thanks :)
